Tuparic
glottolog/glottolog pull request #670
Opened 2021-03-21 09:21 UTC by d97hah

2021-03-21 12:48 UTC, xrotwang requested changes
@d97hah something must have gone wrong: I get:
```
ERROR   Nhlangwini [nhla1239]: unregistered glottocode
ERROR   Ngwena [ngwe1239]: unregistered glottocode
ERROR   Nkwankwa [nkwa1239]: unregistered glottocode
ERROR   Nkumbi [nkum1251]: unregistered glottocode
ERROR   Pungu [pung1240]: unregistered glottocode
ERROR   Hinga [hing1234]: unregistered glottocode
ERROR   Handa (Nkhumbi) [hand1240]: unregistered glottocode
ERROR   Ovanyaneka [ovan1235]: unregistered glottocode
ERROR   Cilenge [cile1234]: unregistered glottocode
ERROR   Mbadja [mbad1234]: unregistered glottocode
ERROR   Mbalanhu [mbal1262]: unregistered glottocode
ERROR   Domdondola [domd1234]: unregistered glottocode
ERROR   Gciriku [gcir1234]: unregistered glottocode
```
which sounds as if `glottocodes.json` wasn't updated correctly. Did you do any editing after running `lff2tree`?

2021-03-21 15:04 UTC, d97hah commented
Not sure what went wrong but now added those to glottocodes.json and
glottolog-admin check does not complain

Pada tanggal Min, 21 Mar 2021 pukul 13.48 Robert Forkel <
***@***.***> menulis:

> ***@***.**** requested changes on this pull request.
>
> @d97hah <https://github.com/d97hah> something must have gone wrong: I get:
>
> ERROR   Nhlangwini [nhla1239]: unregistered glottocode
> ERROR   Ngwena [ngwe1239]: unregistered glottocode
> ERROR   Nkwankwa [nkwa1239]: unregistered glottocode
> ERROR   Nkumbi [nkum1251]: unregistered glottocode
> ERROR   Pungu [pung1240]: unregistered glottocode
> ERROR   Hinga [hing1234]: unregistered glottocode
> ERROR   Handa (Nkhumbi) [hand1240]: unregistered glottocode
> ERROR   Ovanyaneka [ovan1235]: unregistered glottocode
> ERROR   Cilenge [cile1234]: unregistered glottocode
> ERROR   Mbadja [mbad1234]: unregistered glottocode
> ERROR   Mbalanhu [mbal1262]: unregistered glottocode
> ERROR   Domdondola [domd1234]: unregistered glottocode
> ERROR   Gciriku [gcir1234]: unregistered glottocode
>
> which sounds as if glottocodes.json wasn't updated correctly. Did you do
> any editing after running lff2tree?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/glottolog/glottolog/pull/670#pullrequestreview-617016554>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA2QHSFY4QQDXOXM76IYKZDTEXTLLANCNFSM4ZRLPD7Q>
> .
>

2021-03-22 07:25 UTC, xrotwang commented
Hm, that can't be the correct solution yet. You basically just assigned a new Glottocode to Guaratira without changing anything else about it. Maybe you ran `lff2tree` once before adding the dialects and then again after?
Also, you can't just add keys with numbers higher than 1234 to `glottocodes.json`. This will lead to duplicate keys and undefined behaviour, e.g.
```
$ grep pung languoids/glottocodes.json 
    "pung": 1239,
    "pung": 1240
```

2021-03-22 08:29 UTC, xrotwang approved these changes

2021-03-22 08:29 UTC, merged