Nwkukichin
glottolog/glottolog pull request #775
Opened 2021-11-16 23:34 UTC by d97hah

2021-11-18 07:31 UTC, xrotwang requested changes
There are also tree new glottocodes being minted unnecessarily: `ocoy1235`, `sanp1265` and `sant1466`. It seems you didnt't start out with a clone that included commit 034bba63eca1ba49c9d66c593881fed5d7c16ca8

2021-11-18 07:31 UTC, xrotwang commented on languoids/tree/leng1261/leng1262/nort2971/md.ini
> +name = Enxet Sur
This is a regression. I had fixed the names before. This one is Enlhet Norte!

2021-11-18 07:31 UTC, xrotwang commented on languoids/tree/leng1261/leng1262/sout2989/md.ini
> +name = Enlhet Norte
See above.

2021-11-19 07:40 UTC, xrotwang commented
@d97hah `hh:ephonwsoc:Hoenigman:Kanjimei` - used as classification reference for Arafundi - seems to be gone. What should it be replaced with?

2021-11-19 09:27 UTC, d97hah commented
My bad again, how about now?

Pada tanggal Jum, 19 Nov 2021 pukul 08.41 Robert Forkel <
***@***.***> menulis:

> @d97hah <https://github.com/d97hah> hh:ephonwsoc:Hoenigman:Kanjimei -
> used as classification reference for Arafundi - seems to be gone. What
> should it be replaced with?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/glottolog/glottolog/pull/775#issuecomment-973832075>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA2QHSF2ISSPIKF2MZZDWI3UMX5RJANCNFSM5IFR46RQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-19 09:38 UTC, xrotwang commented
Looks promising! :) checks running ...

2021-11-19 09:52 UTC, xrotwang approved these changes

2021-11-19 09:52 UTC, merged