Mel
glottolog/glottolog pull request #784
Opened 2021-12-01 02:13 UTC by d97hah

2021-12-01 08:39 UTC, xrotwang commented
@d97hah I think a sub-group under `Bookkeeping` is a first. What do we expect to happen here? Just the "Pending report release" family to disappear at some point?
I'm not sure something like "provisional bookkeeping languages" help with transparency, so I'd favor just putting the languages directly into `bookkeeping`. They all seem to have valid ISO codes which we don't have in Glottolog yet, so we'd want to have them in any case - whether in `Bookkeeping`, or moved to a regular family lateron.

2021-12-01 09:33 UTC, xrotwang requested changes
See comments

2021-12-01 09:33 UTC, xrotwang commented on languoids/tree/atla1278/volt1241/benu1247/benu1248/taro1265/kwan1287/vagh1247/biji1246/md.ini
> +	UNKNOWN
What is this supposed to mean? Since we don't have `UNKNOWN` in `config/macroareas.ini`, this fails the checks.

2021-12-01 09:36 UTC, d97hah commented
I actually think more subcategories under bookkeeping is helpful towards
transparency. To put the "pending report release" at least differentiates
these from more genuine bookkeeping lgs. The Pending Report Release lgs are
the ones where SIL never releases the underlying reports even after
requests (for most of them, they have not released them even after 14
years). They are quite likely genuine lgs but I want to check the
individual cases.

Pada tanggal Rab, 1 Des 2021 pukul 09.39 Robert Forkel <
***@***.***> menulis:

> @d97hah <https://github.com/d97hah> I think a sub-group under Bookkeeping
> is a first. What do we expect to happen here? Just the "Pending report
> release" family to disappear at some point?
> I'm not sure something like "provisional bookkeeping languages" help with
> transparency, so I'd favor just putting the languages directly into
> bookkeeping. They all seem to have valid ISO codes which we don't have in
> Glottolog yet, so we'd want to have them in any case - whether in
> Bookkeeping, or moved to a regular family lateron.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/glottolog/glottolog/pull/784#issuecomment-983412221>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA2QHSDHTNTNRBULFE5DWVLUOXNLNANCNFSM5JDJOHRA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-12-01 09:44 UTC, xrotwang commented
Ah, ok. If "pending" doesn't necessarily mean we introduce short-lived groups, then that's ok, I guess. Although something like "tags" in the `md.ini` files might be more flexibel - or do we expect to have a hierarchy of categories?

2021-12-01 09:47 UTC, d97hah commented
It should be Africa.

A glitch in my stuff is the cause of the problem. Me fix or you?

Pada tanggal Rab, 1 Des 2021 pukul 10.33 Robert Forkel <
***@***.***> menulis:

> ***@***.**** requested changes on this pull request.
>
> See comments
> ------------------------------
>
> In
> languoids/tree/atla1278/volt1241/benu1247/benu1248/taro1265/kwan1287/vagh1247/biji1246/md.ini
> <https://github.com/glottolog/glottolog/pull/784#discussion_r760004512>:
>
> > @@ -3,8 +3,11 @@
>  name = Bijim
>  level = dialect
>  macroareas =
> -	Africa
> +	UNKNOWN
>
> What is this supposed to mean? Since we don't have UNKNOWN in
> config/macroareas.ini, this fails the checks.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/glottolog/glottolog/pull/784#pullrequestreview-820009784>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA2QHSEDWOYEJ7TSYKV2AB3UOXTX7ANCNFSM5JDJOHRA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-12-01 09:47 UTC, xrotwang commented
> It should be Africa. A glitch in my stuff is the cause of the problem. Me fix or you?

me

2021-12-01 10:48 UTC, xrotwang approved these changes

2021-12-01 10:48 UTC, merged

2021-12-01 13:33 UTC, d97hah commented
A tag in the md.ini is probably a better solution as you suggest. I can
extend the use of hh_ethnologue_comment also for this purpose, and then
it'll be displayed appropriately without any changes to the web app code.
Ok with you?

Pada tanggal Rab, 1 Des 2021 pukul 10.44 Robert Forkel <
***@***.***> menulis:

> Ah, ok. If "pending" doesn't necessarily mean we introduce short-lived
> groups, then that's ok, I guess. Although something like "tags" in the
> md.ini files might be more flexibel - or do we expect to have a hierarchy
> of categories?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/glottolog/glottolog/pull/784#issuecomment-983465085>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA2QHSHFXTIBZ5ENPOPGYHLUOXVA3ANCNFSM5JDJOHRA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-12-01 14:25 UTC, xrotwang commented
I'm torn. For the use case here, the pseudo-sub-family might be the better solution, because moving a language out of there into a regular family won't require any changes in the md.ini - i.e. the actual folder fits the semantics better than a tag, that might end up not being removed when the language is properly sorted. I think the web app won't complain about subfamilies in `Bookkeeping`.

So maybe we start with the sub-folder model until we hit a wall, i.e. find something that should go into two folders - and then switch to tagging.

2021-12-01 15:01 UTC, d97hah commented
OK

Pada tanggal Rab, 1 Des 2021 pukul 15.25 Robert Forkel <
***@***.***> menulis:

> I'm torn. For the use case here, the pseudo-sub-family might be the better
> solution, because moving a language out of there into a regular family
> won't require any changes in the md.ini - i.e. the actual folder fits the
> semantics better than a tag, that might end up not being removed when the
> language is properly sorted. I think the web app won't complain about
> subfamilies in Bookkeeping.
>
> So maybe we start with the sub-folder model until we hit a wall, i.e. find
> something that should go into two folders - and then switch to tagging.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/glottolog/glottolog/pull/784#issuecomment-983693241>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA2QHSGUJ4MKGQZT6A7WXWLUOYV7FANCNFSM5JDJOHRA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-12-04 12:21 UTC, xflr6 commented
Thanks guys.

Deactivated the corresponding `treedb` check in https://github.com/glottolog/treedb/commit/e37e0bbe9bcc36fc1d28b8754d4800c9b7edf738.