Adjusted information on Yola and added some Uralic dialects
glottolog/glottolog pull request #835
Opened 2022-04-04 12:41 UTC by d97hah

2022-04-04 12:49 UTC, xrotwang requested changes

2022-04-04 12:49 UTC, xrotwang commented on languoids/tree/book1242/ndon1252/md.ini
> +	(**hh:g:Kraal:Makonde**, **hh:hlde:Cross-Upcott:KiNgindo**:13-14, 351-358) See also: Makonde [kde].
@d97hah I fixed this already last time, but it keeps coming back. It's *Cross**e***.

2022-04-04 12:49 UTC, xrotwang commented on languoids/tree/ural1272/perm1256/komi1267/komi1268/nort3401/vymm1234/md.ini
> +name = Vym'
Is the trailing single quote `'` intended?

2022-04-04 13:14 UTC, d97hah commented
Re Crosse, sorry, mea culpa!

Yes trailing ' intended in Vym'

Pada tanggal Sen, 4 Apr 2022 pukul 14.49 Robert Forkel <
***@***.***> menulis:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In languoids/tree/book1242/ndon1252/md.ini
> <https://github.com/glottolog/glottolog/pull/835#discussion_r841698185>:
>
> > @@ -44,7 +44,7 @@ multitree = njd
>  [hh_ethnologue_comment]
>  comment = E16/E17/E18/E19/E20/E21/E22/E23/E24 has an entry Ndonde Hamba [njd] in the Lindi region of Tanzania.  While different from its immediate neighbours,
>  	it is a dialect of the language in the Makonde [kde] entry
> -	(**hh:g:Kraal:Makonde**, **hh:hlde:Crosse-Upcott:KiNgindo**:13-14, 351-358) See also: Makonde [kde].
> +	(**hh:g:Kraal:Makonde**, **hh:hlde:Cross-Upcott:KiNgindo**:13-14, 351-358) See also: Makonde [kde].
>
> @d97hah <https://github.com/d97hah> I fixed this already last time, but
> it keeps coming back. It's *Crosse*.
> ------------------------------
>
> In
> languoids/tree/ural1272/perm1256/komi1267/komi1268/nort3401/vymm1234/md.ini
> <https://github.com/glottolog/glottolog/pull/835#discussion_r841699271>:
>
> > @@ -0,0 +1,5 @@
> +# -*- coding: utf-8 -*-
> +[core]
> +name = Vym'
>
> Is the trailing single quote ' intended?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/glottolog/glottolog/pull/835#pullrequestreview-930309167>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA2QHSAXKVE6JL7ELAGFWRLVDLQMRANCNFSM5SPM2OGQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-04-04 15:13 UTC, merged

2022-04-05 18:10 UTC, kealeen commented
@d97hah Hi sorry just a bit confused, will this update on the main glottolog site? Also does it say that the name is Irish Anglo-Norman instead of Yola? I just can’t tell what’s going on apologies for the inconvenience.

2022-04-05 18:35 UTC, xrotwang commented
https://glottolog.org will display the changes once the next version is released - sometime within the the next 2 months, I'd guess.

2022-04-05 19:12 UTC, d97hah commented
Yes, and the language level languoid will be called Irish Anglo-Norman with
two dialects Yola and Fingal. all the best, H

Pada tanggal Sel, 5 Apr 2022 pukul 20.35 Robert Forkel <
***@***.***> menulis:

> https://glottolog.org will display the changes once the next version is
> released - sometime within the the next 2 months, I'd guess.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/glottolog/glottolog/pull/835#issuecomment-1089167701>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA2QHSGR6U6NAFKIN4YCMG3VDSBYTANCNFSM5SPM2OGQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>