Fix hh.bib + misc
glottolog/glottolog pull request #850
Opened 2022-05-20 21:45 UTC by d97hah

closes #796

2022-05-21 06:28 UTC, xrotwang requested changes

2022-05-21 06:28 UTC, xrotwang commented on languoids/tree/arti1236/toki1239/md.ini
> +	UNKNOWN
@d97hah I had fixed (i.e. removed) these before. Maybe you need to fix your side of the machinery that keeps re-inserting?

2022-05-21 13:20 UTC, xrotwang approved these changes

2022-05-21 13:20 UTC, merged

2022-05-22 06:33 UTC, d97hah commented
Sorry my bad. Now fixed (in my code and in repos) with PR

Pada tanggal Sab, 21 Mei 2022 pukul 08.28 Robert Forkel <
***@***.***> menulis:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In languoids/tree/arti1236/toki1239/md.ini
> <https://github.com/glottolog/glottolog/pull/850#discussion_r878653475>:
>
> > @@ -6,6 +6,8 @@ iso639-3 = tok
>  hid = tok
>  countries =
>  	US
> +macroareas =
> +	UNKNOWN
>
> @d97hah <https://github.com/d97hah> I had fixed (i.e. removed) these
> before. Maybe you need to fix your side of the machinery that keeps
> re-inserting?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/glottolog/glottolog/pull/850#pullrequestreview-980793478>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA2QHSEERZRQ5XOMXUCNWOLVLB7CNANCNFSM5WQXAFTQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>